name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_run:
    workflows: [Biome, Tests (Vitest)]
    types:
      - completed

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "24"
      commands: |
        yarn peggy:build
        yarn build
