name: Build
on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "24"
      commands: |
        yarn peggy:build-logs
        yarn peggy:build-llql
        yarn build
