name: Build
on:
  pull_request:
    types:
      - "opened"
      - "reopened"

jobs:
  on-success:
    name: Build
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "22"
      commands: |
        yarn build
