name: Build
on:
  workflow_run:
    workflows:
      - "Biome"
      - "Tests (Vitest)"
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "22"
      commands: |
        yarn build
