name: Biome
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  format-and-lint:
    name: Format & lint
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "22"
      commands: |
        # Format check
        npx biome format . --check
        # Lint / static checks
        npx biome check
