name: Tests (Vitest)
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  vitest:
    name: Run Vitest
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "22"
      commands: |
        # run tests in CI mode
        yarn test
