name: Tests (Vitest)
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  on-success:
    name: Run Vitest
    uses: ./.github/workflows/ci-setup.yml
    with:
      node-version: "24"
      commands: |
        # run tests in CI mode
        yarn test
